/* Oberflächentexte in zwei Sprachen.
   Welche verwendet wird, bestimmt der aktive Kurs: Wer Spanisch lernt, sieht
   die App auf Deutsch. Wer Deutsch lernt, sieht sie auf Spanisch — sonst
   müsste er ja schon Deutsch können, um die App zu bedienen.

   Platzhalter in geschweiften Klammern werden zur Laufzeit ersetzt:
   {ziel} = Sprache, die gelernt wird · {ausgang} = die eigene Sprache */

var TEXTE = {

  /* ===================== DEUTSCH ===================== */
  de: {
    sprachen: { es: 'Spanisch', de: 'Deutsch' },

    'app.untertitel': 'Sprachen lernen, jeden Tag ein Stück',

    /* Kursauswahl */
    'kurs.titel': 'Welche Sprache?',
    'kurs.hinweis': 'Jeder Kurs hat seinen eigenen Fortschritt. Du kannst jederzeit wechseln.',
    'kurs.wechseln': 'Kurs wechseln',
    'kurs.pfad': 'Lernpfad',
    'kurs.neu': 'noch nicht begonnen',
    'kurs.stand': 'Tag {tag} von {gesamt} · {gelernt} Wörter',

    /* Startbildschirm */
    'start.streak': 'Tage in Folge',
    'start.aktiveTage': 'Aktive Tage',
    'start.woerter': 'Gelernte Wörter',
    'start.genauigkeit': 'Genauigkeit',
    'start.problemwoerter': 'Problemwörter',
    'start.tagVon': 'Tag {tag} von {gesamt}',
    'start.grammatik': 'Grammatik:',
    'start.lernen': 'Heute lernen',
    'start.wiederholen': 'Wiederholen',
    'start.erledigt': '✅ Heute schon erledigt — du kannst trotzdem weiter üben.',
    'start.speed': '⚡ Schnell-Wiederholung',
    'start.nurWdh': '🔁 Nur Wiederholen',
    'start.heatmap': 'Letzte 12 Wochen',
    'start.fertigThema': 'Alle Lektionen geschafft! 🏆',
    'start.fertigText': 'Jetzt hältst du dein Wissen mit Wiederholungen frisch.',
    'start.nichtsZuTun': 'Gerade gibt es nichts zu tun. Schau später wieder rein!',

    /* Tagesplan-Checkliste */
    'plan.problem': '⚠️ Problemwörter',
    'plan.faellig': '🔁 Fällige Wiederholungen',
    'plan.vokabeln': '📖 Neue Vokabeln',
    'plan.saetze': '💬 Sätze',
    'plan.grammatik': '📐 Grammatik',

    /* Phasen während der Sitzung */
    'phase.problem': 'Problemwörter',
    'phase.wdh': 'Wiederholung',
    'phase.neu': 'Neue Wörter',
    'phase.satz': 'Sätze',
    'phase.grammatik': 'Grammatik',

    /* Übungen */
    'ueb.pruefen': 'Prüfen',
    'ueb.weiter': 'Weiter',
    'ueb.abschliessen': 'Abschließen',
    'ueb.neuesWort': 'Neues Wort',
    'ueb.wasHeisstAusgang': 'Was heißt das auf {ausgang}?',
    'ueb.wasHeisstZiel': 'Wie heißt das auf {ziel}?',
    'ueb.eingabeZiel': 'Auf {ziel} eingeben…',
    'ueb.eingabeAusgang': 'Auf {ausgang} eingeben…',
    'ueb.satzBilden': 'Bilde den Satz auf {ziel}',
    'ueb.hoerZu': 'Hör zu und schreib auf, was du hörst',
    'ueb.langsamer': '🐢 Langsamer',
    'ueb.nochmal': 'Nochmal abspielen',
    'ueb.luecke': 'Setze die richtige Form ein',
    'ueb.anhoeren': 'Anhören',

    /* Rückmeldung */
    'rueck.fastTitel': '✓ Fast perfekt — die Akzente!',
    'rueck.fastText': 'Richtig geschrieben: <b>{loesung}</b>',
    'rueck.gutTitel': ['¡Muy bien! ✓', '¡Perfecto! ✓', '¡Genial! ✓', '¡Correcto! ✓'],
    'rueck.falschTitel': 'Nicht ganz',
    'rueck.richtigWaere': 'Richtig wäre: <b>{loesung}</b>',
    'rueck.duHattest': 'Du hattest: „{meins}“',
    'rueck.wiederDran': 'Wieder dran in {zeit}',
    'rueck.leechWeg': '🎉 Kein Problemwort mehr!',
    'rueck.leechNeu': '⚠️ Ab jetzt als Problemwort markiert — es kommt in jeder Sitzung wieder, bis es dreimal hintereinander sitzt.',

    /* Abschluss */
    'fertig.perfekt': '¡Perfecto! 🏆',
    'fertig.sehrGut': '¡Muy bien!',
    'fertig.gut': '¡Bien hecho!',
    'fertig.tschuess': '¡Hasta luego!',
    'fertig.tagAbgeschlossen': 'Tag {tag} abgeschlossen',
    'fertig.wdhAbgeschlossen': 'Wiederholung abgeschlossen',
    'fertig.aufgaben': 'Aufgaben',
    'fertig.richtig': 'Richtig',
    'fertig.neueWoerter': 'Neue Wörter',
    'fertig.streak': 'Streak',
    'fertig.nochmalUeben': 'Das üben wir nochmal',
    'fertig.zurueck': 'Zur Übersicht',
    'fertig.duHattest': 'du hattest „{meins}“',

    /* Historie */
    'hist.titel': 'Historie',
    'hist.hinweis': 'Alle Wörter und Sätze, die du schon gesehen hast — sortiert nach Fehlern.',
    'hist.alle': 'Alle',
    'hist.nurLeech': 'Nur Problemwörter',
    'hist.faellig': 'Jetzt fällig',
    'hist.leer': 'Hier ist noch nichts. Lerne erst einen Tag durch.',
    'hist.zuletztGetippt': 'Zuletzt getippt: {eingaben}',
    'hist.neu': 'neu',
    'hist.jetztFaellig': 'jetzt fällig',
    'zeit.stunden': '{n} Std',
    'zeit.tage': '{n} Tage',
    'zeit.monate': '{n} Monate',
    'hist.inStunden': 'in {n} Std',
    'hist.inTagen': 'in {n} Tg',
    'hist.inMonaten': 'in {n} Mon',

    /* Erinnerung */
    'erin.titel': 'Tägliche Erinnerung um 19:30',
    'erin.warumTitel': 'Warum kein „echter“ Handy-Alarm aus der App?',
    'erin.warumText': 'Eine Webseite kann sich nicht selbst melden, wenn sie geschlossen ist — JavaScript läuft nur im offenen Tab. Die Web-Schnittstelle, die das lösen sollte (<em>Notification Triggers</em>), wurde von Google getestet, aber nie ausgeliefert. Deshalb übernimmt dein Kalender oder Wecker den Job: das ist zu 100 % zuverlässig und funktioniert auch offline und im Energiesparmodus.',
    'erin.weg1': 'Weg 1 — Kalendereintrag (ein Klick)',
    'erin.weg1s1': 'Auf den Button unten tippen — es lädt eine Datei <code>lernen-1930.ics</code>.',
    'erin.weg1s2': 'Datei in den Downloads antippen → Google Kalender öffnet sich.',
    'erin.weg1s3': '„Importieren“ bestätigen. Fertig.',
    'erin.icsKnopf': '📅 Kalender-Erinnerung herunterladen',
    'erin.icsHinweis': 'Der Termin wiederholt sich täglich um 19:30 (Zeitzone Europe/Berlin, passt sich also automatisch an Sommer- und Winterzeit an) und enthält den Link zu dieser App.',
    'erin.weg2': 'Weg 2 — Wecker der Uhr-App',
    'erin.weg2s1': 'Uhr-App öffnen → Reiter <strong>Wecker</strong> → <strong>+</strong>',
    'erin.weg2s2': 'Zeit <strong>19:30</strong> einstellen',
    'erin.weg2s3': '<strong>Wiederholen</strong> antippen → alle sieben Wochentage auswählen',
    'erin.weg2s4': 'Als Bezeichnung <strong>„Sprache lernen“</strong> eingeben',
    'erin.weg2s5': 'Speichern',
    'erin.installTitel': 'App aufs Handy legen',
    'erin.installS1': 'Diese Seite in Chrome öffnen',
    'erin.installS2': 'Menü (⋮) → <strong>Zum Startbildschirm hinzufügen</strong>',
    'erin.installS3': 'Ab dann startet sie wie eine normale App, ohne Adressleiste',
    'erin.terminName': 'Sprache lernen',
    'erin.terminText': 'Deine Tageslektion wartet: ',

    /* Einstellungen */
    'einst.titel': 'Einstellungen',
    'einst.ton': 'Aussprache vorlesen',
    'einst.darstellung': 'Darstellung',
    'einst.auto': 'Automatisch',
    'einst.hell': 'Hell',
    'einst.dunkel': 'Dunkel',
    'einst.ziel': 'Aufgaben pro Tag (max.)',
    'einst.zielKurz': '15 — kurz',
    'einst.zielNormal': '25 — normal',
    'einst.zielIntensiv': '40 — intensiv',
    'einst.zielAlles': 'Alles Fällige',
    'einst.sicherung': 'Sicherung',
    'einst.sicherungHinweis': 'Dein Fortschritt liegt nur in diesem Browser. Wenn du die Browserdaten löschst, ist er weg. Lade dir ab und zu eine Sicherung herunter — sie enthält alle Kurse.',
    'einst.export': '⬇️ Fortschritt sichern',
    'einst.import': '⬆️ Sicherung einspielen',
    'einst.reset': 'Zurücksetzen',
    'einst.resetKnopf': 'Fortschritt dieses Kurses löschen',
    'einst.resetAlles': 'Allen Fortschritt löschen (alle Kurse)',
    'einst.importOk': 'Sicherung eingespielt.',
    'einst.importFehler': 'Konnte nicht eingelesen werden: ',
    'einst.resetFrage1': 'Wirklich den Fortschritt dieses Kurses löschen? Streak, gelernte Wörter und Historie sind dann weg.',
    'einst.resetFrage2': 'Ganz sicher? Das lässt sich nicht rückgängig machen.',
    'einst.resetAllesFrage': 'Wirklich ALLE Kurse zurücksetzen?',
    'einst.stimmeFehlt': 'Keine Stimme für {ziel} gefunden. Auf Android: Einstellungen → System → Sprachen → Text-in-Sprache-Ausgabe → passende Sprache herunterladen. Hör-Übungen sind bis dahin ausgeblendet.',
    'einst.stimmeDa': 'Stimme aktiv: {name} ({sprache}).',
    'einst.keineSprachausgabe': 'Dein Browser kann keine Sprachausgabe.',

    /* Menü */
    'menue.start': '🏠 Übersicht',
    'menue.kurse': '🌍 Kurs wechseln',
    'menue.historie': '📜 Historie',
    'menue.erinnerung': '⏰ Erinnerung 19:30',
    'menue.einstellungen': '⚙️ Einstellungen',

    /* Prüfung */
    'pruef.starten': 'Zur Prüfung',
    'pruef.alle': 'Alle freigeschalteten Prüfungen',
    'pruef.abTag': 'ab Tag {tag}',
    'einst.stand': 'Stand der Inhalte',
    'einst.standText': '{kurse} Kurse · {lektionen} Tageslektionen · {pruefungen} Prüfungen',
    'einst.standHinweis': 'Stimmen diese Zahlen nicht mit der Ankündigung überein, lädt dein Gerät noch eine ältere, offline gespeicherte Fassung. Seite einmal neu laden.',
    'pruef.nochTage': '🔒 noch {n} Tage',
    'pruef.nochEinTag': '🔒 noch 1 Tag',
    'pruef.bestandenMit': 'bestanden mit {prozent}%',
    'pruef.nachVorbild': 'nach dem Vorbild von {vorbild}',
    'pruef.nochNicht': 'noch nicht versucht',
    'pruef.besterVersuch': 'bisher bestes Ergebnis: {prozent}%',
    'pruef.soLaeuftAb': 'So läuft die Prüfung ab',
    'pruef.regel1': 'Keine Tipps und keine Hinweise — wie in der echten Prüfung.',
    'pruef.regel2': 'Du bekommst erst am Ende zu sehen, was richtig war.',
    'pruef.regel3': 'Du kannst vor- und zurückblättern und Antworten ändern.',
    'pruef.regel4': 'Du kannst die Prüfung beliebig oft wiederholen.',
    'pruef.teile': 'Die Teile',
    'pruef.punkte': '{n} Punkte',
    'pruef.durchMensch': 'wird von einem Menschen bewertet',
    'pruef.ohneStimme': 'Auf diesem Gerät ist keine passende Stimme installiert. Der Hörteil wird deshalb übersprungen und zählt nicht mit.',
    'pruef.frueherErgebnis': '{anzahl} Versuch(e) bisher · bestes Ergebnis {prozent}%',
    'pruef.jetztStarten': 'Prüfung starten',
    'pruef.zurueck': 'Doch nicht',
    'pruef.aufgabeVon': 'Aufgabe {n} von {gesamt}',
    'pruef.weiter': 'Weiter',
    'pruef.zurueckAufgabe': 'Zurück',
    'pruef.abgeben': 'Abgeben',
    'pruef.aufgeben': 'Prüfung abbrechen',
    'pruef.wirklichAufgeben': 'Prüfung wirklich abbrechen? Deine Antworten gehen verloren.',
    'pruef.nochOffen': 'Du hast {n} Frage(n) nicht beantwortet. Trotzdem abgeben?',
    'pruef.richtig': 'richtig',
    'pruef.falsch': 'falsch',
    'pruef.anhoeren': 'Anhören',
    'pruef.langsam': 'Langsam',
    'pruef.hoerHinweis': 'Der Text wird nicht angezeigt. Du darfst so oft hören, wie du möchtest.',
    'pruef.nichtAutomatisch': 'Diese Aufgabe kann die App nicht automatisch bewerten. Sie zählt nicht in die Punktzahl.',
    'pruef.schreibPlatzhalter': 'Schreibe deine Antwort hier …',
    'pruef.woerter': 'Wörter',
    'pruef.bestanden': 'Bestanden',
    'pruef.nichtBestanden': 'Nicht bestanden',
    'pruef.punkteVon': '{punkte} von {max} Punkten · bestanden ab {grenze}%',
    'pruef.ergebnisTeile': 'Ergebnis nach Teilen',
    'pruef.offeneAufgaben': 'Noch nicht bewertet',
    'pruef.offenErklaerung': 'Freies Schreiben kann die App nicht zuverlässig bewerten. Vergleiche deinen Text mit den Kriterien und der Musterlösung.',
    'pruef.nichtsGeschrieben': 'Du hast nichts geschrieben.',
    'pruef.kriterien': 'Worauf es ankommt',
    'pruef.musterZeigen': 'Musterlösung anzeigen',
    'pruef.durchsicht': 'Durchsicht',
    'pruef.richtigWaere': 'Lösung: {loesung}',

    /* Teilen und Bewertung durch einen Menschen */
    'teilen.zurBewertung': 'Zur Bewertung geben',
    'teilen.nochmalSchicken': 'Noch einmal schicken',
    'teilen.selbstEintragen': 'Bewertung von Hand eintragen',
    'teilen.unterwegs': 'Beim Prüfer',
    'teilen.geteilt': 'Der Link ist auf dem Weg.',
    'teilen.kopiert': 'Der Link liegt in der Zwischenablage — jetzt einfügen und verschicken.',
    'teilen.textKopiert': 'Der Text liegt in der Zwischenablage.',
    'teilen.zuLang': 'Der Text ist zu lang für einen Link. Stattdessen wurde der Textblock vorbereitet — der Prüfer antwortet dann formlos, und du trägst die Bewertung von Hand ein.',
    'teilen.fehlgeschlagen': 'Das hat nicht geklappt. Du kannst den Text auch von Hand kopieren.',
    'teilen.bewertungDa': 'Bewertung',
    'teilen.vonWem': 'von {von}',
    'teilen.eingetroffen': 'Die Bewertung ist eingetroffen.',
    'teilen.unbekannt': 'Zu dieser Bewertung gibt es auf diesem Gerät keine Prüfung. Wurde sie vielleicht auf einem anderen Gerät geschrieben?',
    'teilen.linkKaputt': 'Der Link ist unvollständig angekommen. Lass ihn dir noch einmal schicken.',
    'start.bewertungOffen': '{n} Schreibaufgabe wartet auf Bewertung',
    'start.bewertungOffenMehr': '{n} Schreibaufgaben warten auf Bewertung',
    'start.ansehen': 'ansehen',

    /* Prüfer-Bildschirm */
    'pruefer.betreff': 'Bewertung erbeten',
    'pruefer.kennung': 'Kennung',
    'pruefer.einleitung': 'Jemand lernt {ziel} und bittet dich um eine kurze Rückmeldung zu diesem Text. Es dauert zwei Minuten. Du musst nichts installieren und dich nirgends anmelden.',
    'pruefer.dieAufgabe': 'Die Aufgabe war',
    'pruefer.dieAntwort': 'Der Text',
    'pruefer.woraufAchten': 'Worauf du achten kannst',
    'pruefer.musterZeigen': 'Beispiel für eine gute Lösung',
    'pruefer.bitteBewerten': 'Deine Bewertung',
    'pruefer.richtig': 'richtig',
    'pruefer.teilweise': 'teilweise richtig',
    'pruefer.falsch': 'falsch',
    'pruefer.hinweis': 'Hinweis',
    'pruefer.hinweisPlatzhalter': 'Freiwillig: Was war gut, was könnte besser sein?',
    'pruefer.name': 'Dein Name (freiwillig)',
    'pruefer.zurueckschicken': 'Bewertung zurückschicken',
    'pruefer.keinUrteil': 'Bitte wähle zuerst eine Bewertung aus.',
    'pruefer.fertig': 'Danke! Schick den Link jetzt zurück.',
    'pruefer.gespeichert': 'Bewertung gespeichert.',
    'pruefer.nichtGefunden': 'Diese Prüfung kennt die App nicht. Vielleicht ist sie neuer als diese Version.',
    'pruefer.selbstModus': 'Du trägst hier die Bewertung ein, die du bekommen hast.',
    'pruefer.abbrechen': 'Abbrechen',

    /* Sonstiges */
    'allg.zurueck': 'Zurück',
    'allg.menue': 'Menü',
    'allg.abbrechen': 'Sitzung abbrechen? Deine bisherigen Antworten sind gespeichert.'
  },

  /* ===================== ESPAÑOL ===================== */
  es: {
    sprachen: { es: 'español', de: 'alemán' },

    'app.untertitel': 'Aprende un idioma, un poco cada día',

    'kurs.titel': '¿Qué idioma?',
    'kurs.hinweis': 'Cada curso guarda su propio progreso. Puedes cambiar cuando quieras.',
    'kurs.wechseln': 'Cambiar de curso',
    'kurs.pfad': 'Ruta temática',
    'kurs.neu': 'aún sin empezar',
    'kurs.stand': 'Día {tag} de {gesamt} · {gelernt} palabras',

    'start.streak': 'Días seguidos',
    'start.aktiveTage': 'Días activos',
    'start.woerter': 'Palabras aprendidas',
    'start.genauigkeit': 'Aciertos',
    'start.problemwoerter': 'Palabras difíciles',
    'start.tagVon': 'Día {tag} de {gesamt}',
    'start.grammatik': 'Gramática:',
    'start.lernen': 'Estudiar hoy',
    'start.wiederholen': 'Repasar',
    'start.erledigt': '✅ Ya lo hiciste hoy — puedes seguir practicando igual.',
    'start.speed': '⚡ Repaso rápido',
    'start.nurWdh': '🔁 Solo repasar',
    'start.heatmap': 'Últimas 12 semanas',
    'start.fertigThema': '¡Terminaste todas las lecciones! 🏆',
    'start.fertigText': 'Ahora mantienes lo aprendido con los repasos.',
    'start.nichtsZuTun': 'Ahora mismo no hay nada pendiente. ¡Vuelve más tarde!',

    'plan.problem': '⚠️ Palabras difíciles',
    'plan.faellig': '🔁 Repasos pendientes',
    'plan.vokabeln': '📖 Palabras nuevas',
    'plan.saetze': '💬 Frases',
    'plan.grammatik': '📐 Gramática',

    'phase.problem': 'Palabras difíciles',
    'phase.wdh': 'Repaso',
    'phase.neu': 'Palabras nuevas',
    'phase.satz': 'Frases',
    'phase.grammatik': 'Gramática',

    'ueb.pruefen': 'Comprobar',
    'ueb.weiter': 'Siguiente',
    'ueb.abschliessen': 'Terminar',
    'ueb.neuesWort': 'Palabra nueva',
    'ueb.wasHeisstAusgang': '¿Qué significa en {ausgang}?',
    'ueb.wasHeisstZiel': '¿Cómo se dice en {ziel}?',
    'ueb.eingabeZiel': 'Escribe en {ziel}…',
    'ueb.eingabeAusgang': 'Escribe en {ausgang}…',
    'ueb.satzBilden': 'Forma la frase en {ziel}',
    'ueb.hoerZu': 'Escucha y escribe lo que oyes',
    'ueb.langsamer': '🐢 Más despacio',
    'ueb.nochmal': 'Repetir',
    'ueb.luecke': 'Completa con la forma correcta',
    'ueb.anhoeren': 'Escuchar',

    'rueck.fastTitel': '✓ Casi perfecto — ¡los acentos!',
    'rueck.fastText': 'Se escribe: <b>{loesung}</b>',
    'rueck.gutTitel': ['¡Muy bien! ✓', '¡Perfecto! ✓', '¡Genial! ✓', '¡Correcto! ✓'],
    'rueck.falschTitel': 'No del todo',
    'rueck.richtigWaere': 'Lo correcto sería: <b>{loesung}</b>',
    'rueck.duHattest': 'Escribiste: «{meins}»',
    'rueck.wiederDran': 'Vuelve en {zeit}',
    'rueck.leechWeg': '🎉 ¡Ya no es una palabra difícil!',
    'rueck.leechNeu': '⚠️ Marcada como palabra difícil — volverá en cada sesión hasta que la aciertes tres veces seguidas.',

    'fertig.perfekt': '¡Perfecto! 🏆',
    'fertig.sehrGut': '¡Muy bien!',
    'fertig.gut': '¡Bien hecho!',
    'fertig.tschuess': '¡Hasta luego!',
    'fertig.tagAbgeschlossen': 'Día {tag} completado',
    'fertig.wdhAbgeschlossen': 'Repaso completado',
    'fertig.aufgaben': 'Ejercicios',
    'fertig.richtig': 'Aciertos',
    'fertig.neueWoerter': 'Palabras nuevas',
    'fertig.streak': 'Racha',
    'fertig.nochmalUeben': 'Esto lo practicamos otra vez',
    'fertig.zurueck': 'Volver al inicio',
    'fertig.duHattest': 'escribiste «{meins}»',

    'hist.titel': 'Historial',
    'hist.hinweis': 'Todas las palabras y frases que ya viste — ordenadas por errores.',
    'hist.alle': 'Todas',
    'hist.nurLeech': 'Solo difíciles',
    'hist.faellig': 'Pendientes',
    'hist.leer': 'Aquí todavía no hay nada. Completa primero un día.',
    'hist.zuletztGetippt': 'Última vez escribiste: {eingaben}',
    'hist.neu': 'nueva',
    'hist.jetztFaellig': 'pendiente',
    'zeit.stunden': '{n} h',
    'zeit.tage': '{n} días',
    'zeit.monate': '{n} meses',
    'hist.inStunden': 'en {n} h',
    'hist.inTagen': 'en {n} d',
    'hist.inMonaten': 'en {n} m',

    'erin.titel': 'Recordatorio diario a las 19:30',
    'erin.warumTitel': '¿Por qué la app no avisa sola?',
    'erin.warumText': 'Una página web no puede avisarte sola cuando está cerrada — JavaScript solo funciona con la pestaña abierta. La interfaz que debía resolverlo (<em>Notification Triggers</em>) la probó Google pero nunca la lanzó. Por eso el aviso lo da tu calendario o tu despertador: es 100 % fiable y funciona sin conexión y en modo ahorro de batería.',
    'erin.weg1': 'Opción 1 — Cita en el calendario (un clic)',
    'erin.weg1s1': 'Pulsa el botón de abajo — se descarga un archivo <code>lernen-1930.ics</code>.',
    'erin.weg1s2': 'Abre el archivo en tus descargas → se abre Google Calendar.',
    'erin.weg1s3': 'Confirma «Importar». Listo.',
    'erin.icsKnopf': '📅 Descargar recordatorio de calendario',
    'erin.icsHinweis': 'La cita se repite cada día a las 19:30 (zona horaria Europe/Berlin, así que se ajusta sola al horario de verano) e incluye el enlace a esta app.',
    'erin.weg2': 'Opción 2 — Alarma del reloj',
    'erin.weg2s1': 'Abre la app Reloj → pestaña <strong>Alarma</strong> → <strong>+</strong>',
    'erin.weg2s2': 'Pon la hora <strong>19:30</strong>',
    'erin.weg2s3': 'Pulsa <strong>Repetir</strong> → marca los siete días',
    'erin.weg2s4': 'Ponle el nombre <strong>«Estudiar idioma»</strong>',
    'erin.weg2s5': 'Guarda',
    'erin.installTitel': 'Poner la app en el móvil',
    'erin.installS1': 'Abre esta página en Chrome',
    'erin.installS2': 'Menú (⋮) → <strong>Añadir a pantalla de inicio</strong>',
    'erin.installS3': 'Desde entonces se abre como una app normal, sin barra de direcciones',
    'erin.terminName': 'Estudiar idioma',
    'erin.terminText': 'Tu lección de hoy te espera: ',

    'einst.titel': 'Ajustes',
    'einst.ton': 'Leer la pronunciación',
    'einst.darstellung': 'Apariencia',
    'einst.auto': 'Automático',
    'einst.hell': 'Claro',
    'einst.dunkel': 'Oscuro',
    'einst.ziel': 'Ejercicios por día (máx.)',
    'einst.zielKurz': '15 — corto',
    'einst.zielNormal': '25 — normal',
    'einst.zielIntensiv': '40 — intenso',
    'einst.zielAlles': 'Todo lo pendiente',
    'einst.sicherung': 'Copia de seguridad',
    'einst.sicherungHinweis': 'Tu progreso solo está en este navegador. Si borras los datos del navegador, se pierde. Descarga una copia de vez en cuando — incluye todos los cursos.',
    'einst.export': '⬇️ Guardar progreso',
    'einst.import': '⬆️ Restaurar copia',
    'einst.reset': 'Reiniciar',
    'einst.resetKnopf': 'Borrar el progreso de este curso',
    'einst.resetAlles': 'Borrar todo el progreso (todos los cursos)',
    'einst.importOk': 'Copia restaurada.',
    'einst.importFehler': 'No se pudo leer: ',
    'einst.resetFrage1': '¿Seguro que quieres borrar el progreso de este curso? Perderás la racha, las palabras aprendidas y el historial.',
    'einst.resetFrage2': '¿Totalmente seguro? Esto no se puede deshacer.',
    'einst.resetAllesFrage': '¿Seguro que quieres reiniciar TODOS los cursos?',
    'einst.stimmeFehlt': 'No se encontró una voz en {ziel}. En Android: Ajustes → Sistema → Idiomas → Salida de texto a voz → descarga el idioma. Mientras tanto, los ejercicios de escucha están ocultos.',
    'einst.stimmeDa': 'Voz activa: {name} ({sprache}).',
    'einst.keineSprachausgabe': 'Tu navegador no puede leer en voz alta.',

    'menue.start': '🏠 Inicio',
    'menue.kurse': '🌍 Cambiar de curso',
    'menue.historie': '📜 Historial',
    'menue.erinnerung': '⏰ Recordatorio 19:30',
    'menue.einstellungen': '⚙️ Ajustes',

    /* Examen */
    'pruef.starten': 'Al examen',
    'pruef.alle': 'Todos los exámenes disponibles',
    'pruef.abTag': 'a partir del día {tag}',
    'einst.stand': 'Estado de los contenidos',
    'einst.standText': '{kurse} cursos · {lektionen} lecciones diarias · {pruefungen} exámenes',
    'einst.standHinweis': 'Si estas cifras no coinciden con lo anunciado, tu dispositivo sigue cargando una versión antigua guardada sin conexión. Recarga la página una vez.',
    'pruef.nochTage': '🔒 faltan {n} días',
    'pruef.nochEinTag': '🔒 falta 1 día',
    'pruef.bestandenMit': 'aprobado con {prozent}%',
    'pruef.nachVorbild': 'siguiendo el modelo de {vorbild}',
    'pruef.nochNicht': 'todavía sin intentar',
    'pruef.besterVersuch': 'mejor resultado hasta ahora: {prozent}%',
    'pruef.soLaeuftAb': 'Cómo funciona el examen',
    'pruef.regel1': 'Sin pistas ni ayudas — como en el examen real.',
    'pruef.regel2': 'Verás qué era correcto solo al final.',
    'pruef.regel3': 'Puedes ir adelante y atrás y cambiar tus respuestas.',
    'pruef.regel4': 'Puedes repetir el examen tantas veces como quieras.',
    'pruef.teile': 'Las partes',
    'pruef.punkte': '{n} puntos',
    'pruef.durchMensch': 'lo evalúa una persona',
    'pruef.ohneStimme': 'En este dispositivo no hay una voz adecuada instalada. Por eso se omite la parte de comprensión auditiva y no cuenta.',
    'pruef.frueherErgebnis': '{anzahl} intento(s) · mejor resultado {prozent}%',
    'pruef.jetztStarten': 'Empezar el examen',
    'pruef.zurueck': 'Mejor no',
    'pruef.aufgabeVon': 'Tarea {n} de {gesamt}',
    'pruef.weiter': 'Siguiente',
    'pruef.zurueckAufgabe': 'Atrás',
    'pruef.abgeben': 'Entregar',
    'pruef.aufgeben': 'Abandonar el examen',
    'pruef.wirklichAufgeben': '¿Abandonar el examen? Perderás tus respuestas.',
    'pruef.nochOffen': 'Has dejado {n} pregunta(s) sin responder. ¿Entregar igualmente?',
    'pruef.richtig': 'verdadero',
    'pruef.falsch': 'falso',
    'pruef.anhoeren': 'Escuchar',
    'pruef.langsam': 'Despacio',
    'pruef.hoerHinweis': 'El texto no se muestra. Puedes escucharlo las veces que quieras.',
    'pruef.nichtAutomatisch': 'Esta tarea la aplicación no puede evaluarla automáticamente. No cuenta para la puntuación.',
    'pruef.schreibPlatzhalter': 'Escribe tu respuesta aquí …',
    'pruef.woerter': 'palabras',
    'pruef.bestanden': 'Aprobado',
    'pruef.nichtBestanden': 'No aprobado',
    'pruef.punkteVon': '{punkte} de {max} puntos · se aprueba a partir del {grenze}%',
    'pruef.ergebnisTeile': 'Resultado por partes',
    'pruef.offeneAufgaben': 'Todavía sin evaluar',
    'pruef.offenErklaerung': 'La aplicación no puede evaluar con fiabilidad la escritura libre. Compara tu texto con los criterios y el modelo.',
    'pruef.nichtsGeschrieben': 'No has escrito nada.',
    'pruef.kriterien': 'En qué se fija la evaluación',
    'pruef.musterZeigen': 'Ver el texto modelo',
    'pruef.durchsicht': 'Revisión',
    'pruef.richtigWaere': 'Solución: {loesung}',

    /* Compartir y evaluación por una persona */
    'teilen.zurBewertung': 'Enviar para evaluar',
    'teilen.nochmalSchicken': 'Enviar otra vez',
    'teilen.selbstEintragen': 'Anotar la evaluación a mano',
    'teilen.unterwegs': 'Con el evaluador',
    'teilen.geteilt': 'El enlace va de camino.',
    'teilen.kopiert': 'El enlace está en el portapapeles — pégalo y envíalo.',
    'teilen.textKopiert': 'El texto está en el portapapeles.',
    'teilen.zuLang': 'El texto es demasiado largo para un enlace. En su lugar se ha preparado el bloque de texto — la persona responde libremente y tú anotas la evaluación a mano.',
    'teilen.fehlgeschlagen': 'No ha funcionado. También puedes copiar el texto a mano.',
    'teilen.bewertungDa': 'Evaluación',
    'teilen.vonWem': 'de {von}',
    'teilen.eingetroffen': 'La evaluación ha llegado.',
    'teilen.unbekannt': 'En este dispositivo no hay ningún examen para esta evaluación. ¿Se escribió quizá en otro dispositivo?',
    'teilen.linkKaputt': 'El enlace ha llegado incompleto. Pide que te lo envíen otra vez.',
    'start.bewertungOffen': '{n} tarea de escritura espera evaluación',
    'start.bewertungOffenMehr': '{n} tareas de escritura esperan evaluación',
    'start.ansehen': 'ver',

    /* Pantalla del evaluador */
    'pruefer.betreff': 'Se pide una evaluación',
    'pruefer.kennung': 'Código',
    'pruefer.einleitung': 'Alguien está aprendiendo {ziel} y te pide una valoración breve de este texto. Son dos minutos. No tienes que instalar nada ni registrarte.',
    'pruefer.dieAufgabe': 'La tarea era',
    'pruefer.dieAntwort': 'El texto',
    'pruefer.woraufAchten': 'En qué te puedes fijar',
    'pruefer.musterZeigen': 'Ejemplo de una buena respuesta',
    'pruefer.bitteBewerten': 'Tu valoración',
    'pruefer.richtig': 'correcto',
    'pruefer.teilweise': 'parcialmente correcto',
    'pruefer.falsch': 'incorrecto',
    'pruefer.hinweis': 'Comentario',
    'pruefer.hinweisPlatzhalter': 'Opcional: ¿qué estuvo bien, qué se podría mejorar?',
    'pruefer.name': 'Tu nombre (opcional)',
    'pruefer.zurueckschicken': 'Devolver la evaluación',
    'pruefer.keinUrteil': 'Elige primero una valoración.',
    'pruefer.fertig': '¡Gracias! Envía ahora el enlace de vuelta.',
    'pruefer.gespeichert': 'Evaluación guardada.',
    'pruefer.nichtGefunden': 'La aplicación no conoce este examen. Quizá es más nuevo que esta versión.',
    'pruefer.selbstModus': 'Aquí anotas la evaluación que has recibido.',
    'pruefer.abbrechen': 'Cancelar',

    'allg.zurueck': 'Atrás',
    'allg.menue': 'Menú',
    'allg.abbrechen': '¿Salir de la sesión? Tus respuestas ya están guardadas.'
  }
};

/* ---------------------------------------------------------------------------
   t() holt einen Text in der Sprache des aktiven Kurses und ersetzt die
   Platzhalter. {ziel} und {ausgang} werden automatisch mit den Sprachnamen
   gefüllt, alles andere kannst du selbst mitgeben:
       t('start.tagVon', { tag: 5, gesamt: 60 })
   --------------------------------------------------------------------------- */
var TEXTE_ZWANG = null;   // siehe Prüfer-Modus in js/app.js

function t(schluessel, werte) {
  const kurs = (typeof Kurse !== 'undefined' && Kurse.aktiv()) || null;
  // Im Prüfer-Modus erzwingen wir die Zielsprache des Kurses: Wer einen
  // spanischen Text bewerten soll, ist Spanischsprecher und kann mit einer
  // deutschen Oberfläche nichts anfangen.
  const sprache = TEXTE_ZWANG || (kurs && kurs.ui) || 'de';
  const tabelle = TEXTE[sprache] || TEXTE.de;

  let text = tabelle[schluessel];
  if (text === undefined) text = TEXTE.de[schluessel];
  if (text === undefined) return schluessel;              // fällt auf, statt leer zu sein
  if (Array.isArray(text)) text = text[Math.floor(Math.random() * text.length)];

  const namen = tabelle.sprachen || TEXTE.de.sprachen;
  const alle = Object.assign({
    ziel:    kurs ? namen[kurs.ziel]    : '',
    ausgang: kurs ? namen[kurs.ausgang] : ''
  }, werte || {});

  return text.replace(/\{(\w+)\}/g, (treffer, name) =>
    alle[name] !== undefined ? alle[name] : treffer);
}
